### NumPy Homework

28 points

Due by midnight February 12, 2024

**To avoid erasing the sample output, please insert a new cell above the sample output**. Write your script inside the new cell and run. Verify your output with the sample output. The fish image can be downloaded from the Blackboard

For homework submission, please rename your file using the following format

`firstname_familyname_NumPy_Homework.ipynb`

In [ ]:
Akhila K
700747788



### Task 0
Import the numpy package as np

In [4]:
import numpy as np

### Task 1
Create an numpy array of 10 nines

In [5]:
np.ones(10)*9

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

### Task 2
Create an array of all the odd integers ranging from 11 to 49

In [6]:
np.arange(11,50,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

### Task 3
Create a $10 \times 10$ numpy array with values ranging from 0.01 to 1.0 with step 0.01

In [7]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

### Task 4
Generate a numpy array of 12 random numbers sampled from a standard normal distribution. Please use a random seed 123

In [8]:
np.random.seed(123)
np.random.randn(12)


array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ,
       -0.67888615, -0.09470897])

### Task 5
Create a numpy array of 20 linearly spaced points between 0 and 1

In [9]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Task 6
Create a $6 \times 6$ two-dimensional array `m` with integers ranging from 1 to 36

In [10]:
m=np.arange(1,37).reshape(6,6)
m

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

### Task 7
Using indexing and slicing to extract the following array from array `m`

In [11]:
m[2:,1:]

array([[14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24],
       [26, 27, 28, 29, 30],
       [32, 33, 34, 35, 36]])

### Task 8
Using indexing and slicing to extract the following array from array `m`

In [12]:
m[:3,1:2]

array([[ 2],
       [ 8],
       [14]])

### Task 9
Using indexing and slicing to extract the following array from array `m`

In [13]:
m[-1:-4:-2]

array([[31, 32, 33, 34, 35, 36],
       [19, 20, 21, 22, 23, 24]])

### Task 10
Using indexing and slicing to extract the following array from array `m`

In [14]:
m[-1:-4:-1,::-1]

array([[36, 35, 34, 33, 32, 31],
       [30, 29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20, 19]])

### Task 11
Get the sum of the values in array `m`

In [15]:
np.sum(m)

666

### Task 12
Get the sum of all the columns in array `m`

In [16]:
np.sum(m,axis=0)

array([ 96, 102, 108, 114, 120, 126])

### Task 13
Select all even numbers from array `m`

In [17]:
m[m%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36])

### Task 14
Create a $3 \times 3 \times 5$ three-dimensional array with integers from `[0, 44]`

In [18]:
arr=np.arange(0,45).reshape(3,3,5)

### Task 15
Replace the elements within the two red boxes to 1

<div>
<img src="attachment:f1.png" width="210" align="left"/>
</div>

In [19]:
arr[1,0::2][0:,1:4]=1
arr_=arr
arr_

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15,  1,  1,  1, 19],
        [20, 21, 22, 23, 24],
        [25,  1,  1,  1, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

### Task 16
Replace all the even numbers in the array to 0

In [20]:
arr2=arr_.ravel()
for i in arr2:
    if(i%2 == 0):
        arr2[i] = 0
arr2=arr2.reshape(3,3,5)
arr2

array([[[ 0,  1,  0,  3,  0],
        [ 5,  0,  7,  0,  9],
        [ 0, 11,  0, 13,  0]],

       [[15,  1,  1,  1, 19],
        [ 0, 21,  0, 23,  0],
        [25,  1,  1,  1, 29]],

       [[ 0, 31,  0, 33,  0],
        [35,  0, 37,  0, 39],
        [ 0, 41,  0, 43,  0]]])

### Task 17
Replace all the odd numbers in the array to 1

In [21]:
arr3=arr2.ravel()
for i in arr3:
    if(i%2 != 0):
        arr3[i] = 1
arr3=arr3.reshape(3,3,5)
arr3

array([[[0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [0, 1, 0, 1, 0]],

       [[1, 1, 1, 1, 1],
        [0, 1, 0, 1, 0],
        [1, 1, 1, 1, 1]],

       [[0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [0, 1, 0, 1, 0]]])

### Task 18
Change the array shape to $9 \times 5$

In [22]:
arr4=arr3.reshape(9,5)
arr4

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

### Task 19
Creates two $2 \times 4$ matrices with integers from `[0, 7]`

In [23]:
d1, d2 = np.arange(0, 8).reshape(2,4), np.arange(0, 8).reshape(2,4)
print(d1,d2,sep='\n')

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


### Task 20
Vertically stack the two matrices

In [24]:
vert = np.vstack([d1,d2])
vert

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

### Task 21
Split the big matrix into two $4 \times 2$ small matrices

In [25]:
l,r=np.hsplit(vert,[2])
print(l)
print(r)

[[0 1]
 [4 5]
 [0 1]
 [4 5]]
[[2 3]
 [6 7]
 [2 3]
 [6 7]]


### Task 22
Duplicate one of the resulting matrices once horizontally

In [26]:
np.tile(r, 2)

array([[2, 3, 2, 3],
       [6, 7, 6, 7],
       [2, 3, 2, 3],
       [6, 7, 6, 7]])

### Task 23
Create an array shown below

<div>
<img src="attachment:f1.png" width="200" align="left"/>
</div>

In [27]:
z=np.arange(0.,4.)
np.tile(z, (8, 1))

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

### Task 24
Generate a numpy array of 12 random numbers sampled from a standard normal distribution. Please use a random seed 123. Find the first three smallest values from the array

In [28]:
np.random.seed(123)
num1=np.random.normal(0,1,12)
num2=np.sort(num1)
num2[0:3]

array([-2.42667924, -1.50629471, -1.0856306 ])

### Task 25
Generate a numpy array with integer from `1, 2, 3, ..., 30`. Without using loop, find the number of values in the array which are divisible by 2 or 3

In [29]:
n=np.arange(1,31)
n[np.where((n % 2 == 0)|(n % 3== 0))].size

20

### Task 26
Generate a $6 \times 5$ numpy array with integer from `1, 2, 3, ..., 30`. Without using loop, set the even number in the array by 1 and odd number in the array by -1

In [30]:
n=np.arange(1,31).reshape(6,5)

n[0:5:2,0:5:2]=np.full((3,3),-1)
n[0:5:2,1:4:2]=np.ones((3,2))
n[1:6:2,1:5:2]=np.full((3,2),-1)
n[1:6:2,0:6:2]=np.ones((3,3))
n

array([[-1,  1, -1,  1, -1],
       [ 1, -1,  1, -1,  1],
       [-1,  1, -1,  1, -1],
       [ 1, -1,  1, -1,  1],
       [-1,  1, -1,  1, -1],
       [ 1, -1,  1, -1,  1]])

### Task 27
Create the following effect for the fish image (flip the left and right sides of the image)

In [31]:
import numpy as np
from PIL import Image
img1 = np.array(Image.open('fish.jpeg'))
img2 = Image.fromarray(np.fliplr(img1))
img2

ModuleNotFoundError: No module named 'PIL'

### Task 28
Given a $2 \times 3$ numpy array
```python
arr = array([[1, 2, 3],
             [4, 5, 6]])
```
, produce the following array using array concatenation
```python
arr = array([[1, 2, 3, 1, 2, 3],
             [4, 5, 6, 4, 5, 6],
             [1, 2, 3, 1, 2, 3],
             [4, 5, 6, 4, 5, 6]])
```

In [32]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
res = np.concatenate((arr, arr), axis=1)
res_final= np.concatenate((res, res), axis=0)
res_final

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])